/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Global hotkey manager. */
export declare class HotkeyManager {
  /**
   * Create a new hotkey manager.
   *
   * Must be called on a thread with an active event loop.
   */
  constructor()
  /**
   * Register a hotkey from a string like "Ctrl+Shift+M".
   *
   * Returns the hotkey ID.
   */
  register(hotkey: string): number
  /** Unregister a hotkey by ID. */
  unregister(id: number): void
  /** Unregister all hotkeys. */
  unregisterAll(): void
  /**
   * Poll for a hotkey event (non-blocking).
   *
   * Returns null if no event is available.
   */
  pollEvent(): JsHotkeyEvent | null
  /**
   * Listen for hotkey events using a callback.
   *
   * The callback receives standard Node.js arguments: `(err, event)`
   */
  listen(callback: ((err: Error | null, arg: JsHotkeyEvent) => any)): void
  /** Get the list of registered hotkey IDs. */
  registeredIds(): Array<number>
}
export type JsHotkeyManager = HotkeyManager

/** Input simulator for keyboard and mouse actions. */
export declare class InputSimulator {
  /** Create a new input simulator. */
  constructor()
  /** Type a string of text. */
  typeText(text: string): void
  /**
   * Perform a key action.
   *
   * `key`: Key name like "enter", "a", "F5", etc.
   * `mode`: "click", "press", or "release".
   */
  keyAction(key: string, mode: string): void
  /**
   * Perform a mouse button action.
   *
   * `button`: "left", "right", or "middle".
   * `mode`: "click", "press", or "release".
   */
  mouseClick(button: string, mode: string): void
  /**
   * Move the mouse cursor.
   *
   * `mode`: "absolute" or "relative".
   */
  mouseMove(x: number, y: number, mode: string): void
  /**
   * Scroll the mouse wheel.
   *
   * `axis`: "vertical" or "horizontal".
   */
  scroll(axis: string, amount: number): void
}
export type JsInputSimulator = InputSimulator

/** A hotkey event returned from polling. */
export interface JsHotkeyEvent {
  /** The hotkey ID. */
  id: number
  /** The state: "pressed" or "released". */
  state: string
}
